#pragma once

// CHAPTER 1

//#define GETTING_STARTED
//#define VARIABLE_AND_ARITHMETIC_EXPRESSIONS
//#define FOR_STATEMENT
//#define SYMBOLIC_CONSTANTS
//#define CHARACTER_INPUT_AND_OUTPUT
//#define ARRAYS
//#define FUNCTIONS
#define ARGUMENTS_CALL_BY_VALUE

// END OF CHAPTER1

